<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script
            src="https://code.jquery.com/jquery-3.5.1.js"
            integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
            crossorigin="anonymous"></script>
    <title>Main Page</title>
</head>
<body>

<p>Home Page</p>
<input class="form-control col-4" id="search_substring" name="search_substring" type="text" placeholder="Search...">

<div>
    <table id="music_table">

    </table>
</div>

<script src="/js/main_page_script.js"></script>
</body>
</html>