<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<h3>Add your's tea in collection</h3>
<form method="post" action="/teas">
    <input type="text" name="name" placeholder="Name of Tea">
    <input type="text" name="description" placeholder="Description of Tea">
    <input type="submit" name="addTeaButton" value="Add Tea">
</form>
</body>
</html>